const POLEARM_STYLE_DATA = {
	"metaData": {
		"weapon": "Polearm",
		"trainedValue": 1
	},
	"styles": [{
		"class": ["Armsman"],
		"name": "Pole Thrash",
		"level": 1,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Very Low",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman"],
		"name": "Impale",
		"level": 2,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Very Low",
		"hit": "No Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Cross",
		"level": 4,
		"open": "To side of target",
		"followup": ["Disabler"],
		"end": "Low",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 11 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Deflect",
		"level": 6,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "None",
		"hit": "No Bonus",
		"def": "High Bonus",
		"effect": "Increases your threat to monster targets by 0 damage."
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Faith",
		"level": 8,
		"open": "Any",
		"followup": ["Defender's Courage"],
		"end": "High",
		"dmg": "Low",
		"hit": "Low Bonus",
		"def": "Low Penalty",
		"effect": "4 damage every 5.0 sec for 25 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Executioner",
		"level": 10,
		"open": "You Parry",
		"followup": ["Defender's Advance"],
		"end": "Medium",
		"dmg": "High",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": "Targets attack speed reduced by 16% for 20 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Distract",
		"level": 12,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Medium",
		"hit": "Low Bonus",
		"def": "Medium Penalty",
		"effect": "Increases your threat to monster targets by 275 damage."
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Courage",
		"level": 15,
		"open": "Defender's Faith",
		"followup": null,
		"end": "Medium",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target's attack speed reduced by 20% for 20 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Crippling Blow",
		"level": 18,
		"open": "To side of target",
		"followup": ["Mangle"],
		"end": "Medium",
		"dmg": "Low",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 11 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Disabler",
		"level": 21,
		"open": "Defender's Cross",
		"followup": null,
		"end": "Low",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target's attack speed reduced by 21% for 20 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Phalanx",
		"level": 25,
		"open": "Behind target",
		"followup": ["Defender's Revenge"],
		"end": "Medium",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 15 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Mangle",
		"level": 29,
		"open": "Crippling Blow",
		"followup": null,
		"end": "Medium",
		"dmg": "Medium",
		"hit": "No Bonus",
		"def": "No Bonus",
		"effect": "Target cannot move or take any other action for 6 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Rage",
		"level": 34,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman"],
		"name": "Poleaxe",
		"level": 39,
		"open": "To side of target",
		"followup": ["Defender's Aegis"],
		"end": "High",
		"dmg": "High",
		"hit": "High Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 15 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Revenge",
		"level": 44,
		"open": "Phalanx",
		"followup": null,
		"end": "Medium",
		"dmg": "Very High",
		"hit": "Very High Bonus",
		"def": "No Bonus",
		"effect": "Target cannot move or take any other action for 9 seconds."
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Advance",
		"level": 48,
		"open": "Executioner",
		"followup": null,
		"end": "High",
		"dmg": "Very High",
		"hit": "Low Bonus",
		"def": "Medium Bonus",
		"effect": "20 damage every 4.0 sec for 20 seconds"
	},
	{
		"class": ["Armsman"],
		"name": "Defender's Aegis",
		"level": 50,
		"open": "Poleaxe",
		"followup": null,
		"end": "Medium",
		"dmg": "Very High",
		"hit": "High Bonus",
		"def": "Low Bonus",
		"effect": "32 damage every 4.0 sec for 20 seconds."
	}
	
]};

const SLASH_STYLE_DATA = {
	"metaData": {
		"weapon": "Slash",
		"trainedValue": 1
	},
	"styles": [{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Ruby Slash",
		"level": 1,
		"open": "Any",
		"followup": ["Emerald Slash"],
		"end": "Low",
		"dmg": "Very Low",
		"hit": "No Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Emerald Slash",
		"level": 2,
		"open": "Ruby Slash",
		"followup": null,
		"end": "Low",
		"dmg": "Low",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "8 damage every 4.0 seconds for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Cross Slash",
		"level": 4,
		"open": "In front of target",
		"followup": ["Bloodletter"],
		"end": "Low",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "Medium Bonus",
		"effect": "Target's attack speed reduced by 16% for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Uppercut",
		"level": 6,
		"open": "Any",
		"followup": ["Opal Slash", "Cleave"],
		"end": "Medium",
		"dmg": "Low",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Enrage",
		"level": 8,
		"open": "Any",
		"followup": ["Sapphire Slash"],
		"end": "Low",
		"dmg": "Medium",
		"hit": "No Bonus",
		"def": "Medium Penalty",
		"effect": "Increases your threat to monster targets by 275 damage."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Bloodletter",
		"level": 10,
		"open": "Cross Slash",
		"followup": null,
		"end": "Medium",
		"dmg": "Low",
		"hit": "High Bonus",
		"def": "Medium Bonus",
		"effect": "13 damage every 4.0 seconds for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Reflect",
		"level": 12,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "None",
		"hit": "No Bonus",
		"def": "Medium Bonus",
		"effect": "Increases your threat to monster targets by 0 damage."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Opal Slash",
		"level": 15,
		"open": "Uppercut",
		"followup": null,
		"end": "Medium",
		"dmg": "Low",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "13 damage every 4.0 seconds for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Riposte",
		"level": 18,
		"open": "You Block",
		"followup": ["Befuddler"],
		"end": "Low",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "Medium Bonus",
		"effect": "Target's attack speed reduced by 21% for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Side Slicer",
		"level": 21,
		"open": "To side of target",
		"followup": null,
		"end": "Low",
		"dmg": "Medium",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 14 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Cleave",
		"level": 25,
		"open": "Uppercut",
		"followup": null,
		"end": "Low",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "20 damage every 4.0 seconds for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Amethyst Slash",
		"level": 29,
		"open": "Any",
		"followup": null,
		"end": "Medium",
		"dmg": "High",
		"hit": "High Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Befuddler",
		"level": 34,
		"open": "Riposte",
		"followup": null,
		"end": "Medium",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target cannot move or take any other action for 6 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Back Slash",
		"level": 39,
		"open": "Behind target",
		"followup": ["Diamond Slash"],
		"end": "High",
		"dmg": "High",
		"hit": "High Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 19 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Sapphire Slash",
		"level": 44,
		"open": "Enrage",
		"followup": null,
		"end": "Low",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "High Penalty",
		"effect": "26 damage every 4.0 seconds for 20 seconds."
	},
	{
		"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
		"name": "Diamond Slash",
		"level": 50,
		"open": "Back Slash",
		"followup": null,
		"end": "High",
		"dmg": "High",
		"hit": "Very High Bonus",
		"def": "No Bonus",
		"effect": "Target's attack speed reduced by 34% for 20 seconds."
	}
]};

const TWO_HANDED_STYLE_DATA = {
	"metaData": {
		"weapon": "Two Handed",
		"trainedValue": 1,
	},
	"styles": [{
		"class": ["Armsman", "Paladin"],
		"name": "Quarter Moon",
		"level": 1,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Very Low",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Half Moon",
		"level": 2,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Very Low",
		"hit": "No Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Double Back",
		"level": 4,
		"open": "In front of target",
		"followup": ["Two Fists"],
		"end": "Medium",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target's attack speed reduced by 16% for 20 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Rile",
		"level": 6,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "Medium",
		"hit": "High Bonus",
		"def": "Medium Penalty",
		"effect": "Increases your threat to monster targets by 275 damage."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Pacify",
		"level": 8,
		"open": "Any",
		"followup": null,
		"end": "Low",
		"dmg": "None",
		"hit": "No Bonus",
		"def": "High Bonus",
		"effect": "Increases your threat to monster targets by 0 damage."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Two Fists",
		"level": 10,
		"open": "Double Back",
		"followup": null,
		"end": "Medium",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "8 damage every 5.0 sec for 20 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Bone Bruiser",
		"level": 12,
		"open": "Any",
		"followup": null,
		"end": "Medium",
		"dmg": "Low",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": "Target's attack speed reduced by 18% for 20 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Onslaught",
		"level": 15,
		"open": "To side of target",
		"followup": ["Two Moons"],
		"end": "Medium",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 14 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Fury",
		"level": 18,
		"open": "You Parry",
		"followup": ["Recenter"],
		"end": "Low",
		"dmg": "Medium",
		"hit": "High Bonus",
		"def": "High Penalty",
		"effect": "13 damage every 4.0 sec for 20 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Bone Splitter",
		"level": 21,
		"open": "In front of target",
		"followup": ["Bone Breaker"],
		"end": "Medium",
		"dmg": "Medium",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Recenter",
		"level": 25,
		"open": "Fury",
		"followup": null,
		"end": "Low",
		"dmg": "High",
		"hit": "Low Bonus",
		"def": "High Bonus",
		"effect": "Target's attack speed reduced by 26% for 20 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Bone Breaker",
		"level": 29,
		"open": "Bone Splitter",
		"followup": null,
		"end": "Medium",
		"dmg": "High",
		"hit": "Low Bonus",
		"def": "No Bonus",
		"effect": "20 damage every 4.0 sec for 20 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Obfuscate",
		"level": 34,
		"open": "Any",
		"followup": null,
		"end": "Medium",
		"dmg": "Medium",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": null
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Doubler",
		"level": 39,
		"open": "Behind target",
		"followup": ["Sun and Moon"],
		"end": "Medium",
		"dmg": "High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target moves 40% slower for 23 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Two Moons",
		"level": 44,
		"open": "Onslaught",
		"followup": null,
		"end": "Low",
		"dmg": "Very High",
		"hit": "High Bonus",
		"def": "No Bonus",
		"effect": "Target cannot move or take any other action for 9 seconds."
	},
	{
		"class": ["Armsman", "Paladin"],
		"name": "Sun and Moon",
		"level": 50,
		"open": "Doubler",
		"followup": null,
		"end": "Medium",
		"dmg": "Very High",
		"hit": "Medium Bonus",
		"def": "No Bonus",
		"effect": "Target cannot move or take any other action for 7 seconds."
	}
]};



/*  style template

		"class": [""],
		"name": "",
		"level": ,
		"open": "",
		"followup": ,
		"end": "",
		"dmg": "",
		"hit": "",
		"def": "",
		"effect":

*/