const BLADES_SPEC_DATA = {
	"metaData": {
		"spec": "Blades",
		"type": "Combat",
		"weapon": "Blades",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Shining Blade",
			"level": 1,
			"open": "Any",
			"followup": ["Shimmering Blade"],
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Shimmering Blade",
			"level": 2,
			"open": "Shining Blade",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Bard", "Nightshade", "Ranger"],
			"name": "Return Blade",
			"level": 4,
			"open": "You Evade",
			"followup": ["Lunging Blade"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Return Blade",
			"level": 4,
			"open": "You Parry",
			"followup": ["Lunging Blade"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Taunting Blade",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Mediumn Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Enervating Blade",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Glowing Blade",
			"level": 10,
			"open": "To side of target",
			"followup": ["Auroric Blade"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 14 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Lunging Blade",
			"level": 12,
			"open": "Return Blade",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Auroric Blade",
			"level": 15,
			"open": "Glowing Blade",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 20% for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Fire Blade",
			"level": 18,
			"open": "Any",
			"followup": ["Spectrum Blade"],
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": null
		},
		{
			"class": ["Bard", "Nightshade", "Ranger"],
			"name": "Horizon Blade",
			"level": 21,
			"open": "You Evade",
			"followup": ["Dancing Blade"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Blademaster"],
			"name": "Horizon Blade",
			"level": 21,
			"open": "You Parry",
			"followup": ["Dancing Blade"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Champion", "Hero", "Warden"],
			"name": "Horizon Blade",
			"level": 21,
			"open": "You Block",
			"followup": ["Dancing Blade"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Bard", "Nightshade", "Ranger"],
			"name": "Kinetic Blade",
			"level": 25,
			"open": "You Evade",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Kinetic Blade",
			"level": 25,
			"open": "You Parry",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Dancing Blade",
			"level": 29,
			"open": "Horizon Blade",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 6 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Stone Shaper",
			"level": 32,
			"open": "Any",
			"followup": ["Stone Breaker", "Stone Temper"],
			"end": "Very High",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": "Increases your Blades by 25% for 25 seconds."
		},
		{
			"class": ["Bard", "Champion", "Hero", "Ranger", "Warden"],
			"name": "Revenging Blade",
			"level": 34,
			"open": "Behind target",
			"followup": ["Brilliant Blade"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Target moves 40% slower for 19 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade"],
			"name": "Revenging Blade",
			"level": 34,
			"open": "Behind target",
			"followup": ["Brilliant Blade"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Spectrum Blade",
			"level": 39,
			"open": "Fire Blade",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Medium Bonus",
			"effect": "Target's attack speed reduced by 30% for 20 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Stone Temper",
			"level": 40,
			"open": "Stone Shaper",
			"followup": null,
			"end": "Very High",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Low Penalty",
			"effect": "Reduces the target's absorption (ABS) by 50% for 20 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Stone Breaker",
			"level": 40,
			"open": "Stone Shaper",
			"followup": null,
			"end": "Very High",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "A negative effect is removed from the target.\n\nRemoves any ABS debuff from the target.\nRemoves any Weaponskill buff from yourself."
		},
		{
			"class": ["Bard", "Champion", "Hero", "Warden"],
			"name": "Prismatic Blade",
			"level": 44,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Prismatic Blade",
			"level": 44,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Warden"],
			"name": "Brilliant Blade",
			"level": 50,
			"open": "Revenging Blade",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Very High Bonus",
			"def": "No Bonus",
			"effect": "32 damage every 4.0 sec for 20 seconds."
		}
	]
};

const BLUNT_SPEC_DATA = {
	"metaData": {
		"spec": "Blunt",
		"type": "Combat",
		"weapon": "Blunt",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Contusions",
			"level": 1,
			"open": "Any",
			"followup": ["Bludgeon"],
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Bludgeon",
			"level": 2,
			"open": "Contusions",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster"],
			"name": "Bruiser",
			"level": 4,
			"open": "You Evade",
			"followup": ["Impact"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 3 seconds."
		},
		{
			"class": ["Champion", "Hero", "Warden"],
			"name": "Bruiser",
			"level": 4,
			"open": "You Block",
			"followup": ["Impact"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannnot move or take any other action for 3 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Blunt Trauma",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Slam",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Side Bash",
			"level": 10,
			"open": "To side of target",
			"followup": ["Unstoppable Force"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 20% for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Impact",
			"level": 12,
			"open": "Bruiser",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Bard"],
			"name": "Windfall",
			"level": 15,
			"open": "Target Evade",
			"followup": ["Bone Crusher"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 22% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Windfall",
			"level": 15,
			"open": "You Parry",
			"followup": ["Bone Crusher"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 22% for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Force of Might",
			"level": 18,
			"open": "Any",
			"followup": null,
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Unstoppable Force",
			"level": 21,
			"open": "Side Bash",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target moves 40% slower for 19 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Forest Protector",
			"level": 23,
			"open": "Any",
			"followup": ["Forest Executioner"],
			"end": "Very High",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "Grants a 50.0% enhancement to the effectiveness of heal spells cast by the target."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Back Crush",
			"level": 25,
			"open": "Behind target",
			"followup": ["Crushing Blow"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Target moves 40% slower for 15 seconds.\n\nThe snare component will not fire for Blademasters."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Bone Crusher",
			"level": 29,
			"open": "Windfall",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Forest Executioner",
			"level": 32,
			"open": "Forest Protector",
			"followup": null,
			"end": "Very High",
			"dmg": "Very High",
			"hit": "Low Penalty",
			"def": "Low Bonus",
			"effect": "Imposes a -50.0% penalty to the effectiveness of heal spells cast by the target."
		},
		{
			"class": ["Bard", "Champion", "Hero", "Warden"],
			"name": "Mauler",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster"],
			"name": "Mauler",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Stunning Blow",
			"level": 39,
			"open": "You Parry",
			"followup": ["Devastating Blow"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 30% for 20 seconds."
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Crushing Blow",
			"level": 44,
			"open": "Back Crush",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Very High Bonus",
			"def": "Low Bonus",
			"effect": null
		},
		{
			"class": ["Bard", "Blademaster", "Champion", "Hero", "Warden"],
			"name": "Devastating Blow",
			"level": 50,
			"open": "Stunning Blow",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 10 seconds."
		}
	]
};

const CELTIC_DUAL_SPEC_DATA = {
	"metaData": {
		"spec": "Celtic Dual",
		"type": "Combat",
		"weapon": "Celtic Dual",
		"trainedValue": 1
	},
	"styles": [ 
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Nova",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Misty Gloom",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Blinding Rain",
			"level": 4,
			"open": "You Evade",
			"followup": ["Blizzard"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Squall",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Snow Shower",
			"level": 8,
			"open": "In front of target",
			"followup": ["Gale"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Gale",
			"level": 10,
			"open": "Snow Shower",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Blizzard",
			"level": 12,
			"open": "Blinding Rain",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 21% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Thunderstorm",
			"level": 15,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Ice Storm",
			"level": 18,
			"open": "To side of target",
			"followup": ["Tempest"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade"],
			"name": "Hurricane",
			"level": 21,
			"open": "Behind target",
			"followup": ["Supernova"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": null
		},
		{
			"class": ["Ranger"],
			"name": "Hurricane",
			"level": 21,
			"open": "Behind target",
			"followup": ["Supernova"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Target moves 40% slower for 19 seconds."
		},
		{
			"class": ["Blademaster"],
			"name": "Tornado",
			"level": 25,
			"open": "You Parry",
			"followup": ["Twin Star"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Medium Bonus",
			"effect": "Reduces the target's armor factor (AF) by 100 for 15 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Tornado",
			"level": 25,
			"open": "You Evade",
			"followup": ["Twin Star II"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Medium Bonus",
			"effect": "Reduces the target's armor factor (AF) by 50 for 15 seconds."
		},
		{
			"class": ["Ranger"],
			"name": "Tornado",
			"level": 25,
			"open": "You Evade",
			"followup": ["Twin Star II", "Twin Star I"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Medium Bonus",
			"effect": "Reduces the target's armor factor (AF) by 50 for 15 seconds."
		},
		{
			"class": ["Blademaster"],
			"name": "Tempest",
			"level": 29,
			"open": "Ice Storm",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Mediumn Bonus",
			"def": "No Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Nightshade", "Ranger"],
			"name": "Tempest",
			"level": 29,
			"open": "Ice Storm",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Mediumn Bonus",
			"def": "No Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Ranger"],
			"name": "Twin Star I",
			"level": 33,
			"open": "Tornado",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Mediumn Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Meteor Shower",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Ranger"],
			"name": "Frozen Comet",
			"level": 35,
			"open": "In front of target",
			"followup": ["Solar Flare"],
			"end": "High",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "The target is rooted in place for 15 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade"],
			"name": "Solar Flare",
			"level": 39,
			"open": "To side of target",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target moves 40% slower for 23 seconds."
		},
		{
			"class": ["Ranger"],
			"name": "Solar Flare",
			"level": 39,
			"open": "Frozen Comet",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 34% for 20 seconds."
		},
		{
			"class": ["Blademaster"],
			"name": "Twin Star",
			"level": 44,
			"open": "Tornade",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Nightshade", "Ranger"],
			"name": "Twin Star II",
			"level": 44,
			"open": "Tornade",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Blademaster"],
			"name": "Supernova",
			"level": 50,
			"open": "Hurricane",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Supernova",
			"level": 50,
			"open": "Hurricane",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 34% for 20 seconds."
		},
		{
			"class": ["Ranger"],
			"name": "Supernova",
			"level": 50,
			"open": "Hurricane",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		}
	]
};

const CELTIC_SPEAR_SPEC_DATA = {
	"metaData": {
		"spec": "Celtic Spear",
		"type": "Combat",
		"weapon": "Celtic Spear",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Hero"],
			"name": "Falcon's Talon",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Hero"],
			"name": "Hunter's Spear",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Hero"],
			"name": "Entrap",
			"level": 4,
			"open": "You Evade",
			"followup": ["Hunter's Largess"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Hunter's Boon",
			"level": 6,
			"open": "In front of target",
			"followup": ["Hunter's Lance"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Hunter's Barb",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Hero"],
			"name": "Forest Spear",
			"level": 10,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Hero"],
			"name": "Hunter's Largess",
			"level": 12,
			"open": "Entrap",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Hunter's Lance",
			"level": 15,
			"open": "Hunter's Boon",
			"followup": null,
			"end": "High",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Javelin",
			"level": 18,
			"open": "To side of target",
			"followup": ["Hunter's Gift"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 21% for 20 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Tracking Spear",
			"level": 21,
			"open": "Behind target",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Hunter's Gift",
			"level": 25,
			"open": "Javelin",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 6 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Hawk's Talon",
			"level": 29,
			"open": "You Parry",
			"followup": 29,
			"end": "Medium",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Eagle Talon",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Hero"],
			"name": "Wyvern Talon",
			"level": 39,
			"open": "Hawk's Talon",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Dragon Talon",
			"level": 44,
			"open": "To side of target",
			"followup": ["Cuchulain's Revenge"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 23 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Cuchulain's Revenge",
			"level": 50,
			"open": "Dragon Talon",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "32 damage every 4.0 sec for 20 seconds."
		}
	]
};

const CRITICAL_STRIKE_SPEC_DATA = {
	"metaData": {
		"spec": "Critical Strike",
		"type": "Combat",
		"weapon": "",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["NightShade"],
			"name": "Puncture Defense",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Nightshade"],
			"name": "Backstab",
			"level": 2,
			"open": "Behind target, must be stealthed.",
			"followup": ["Eviscerate"],
			"end": "Low",
			"dmg": "Devastating",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Target cannot move or take any other action for 2 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Eviscerate",
			"level": 4,
			"open": "Backstab",
			"followup": ["Kidney Rupture"],
			"end": "Medim",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Kidney Rupture",
			"level": 6,
			"open": "Eviscerate",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Medium Penalty",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Pincer",
			"level": 8,
			"open": "To side of target",
			"followup": ["Leaper"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "High Penalty",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Backstab II",
			"level": 10,
			"open": "Behind target, must be stealthed.",
			"followup": ["Thigh Cut"],
			"end": "Low",
			"dmg": "Devastating",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 3 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Hamstring",
			"level": 12,
			"open": "You Evade",
			"followup": ["Achilles' Heel"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 21% for 20 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Thigh Cut",
			"level": 15,
			"open": "Backstab II",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "26 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Garrote",
			"level": 18,
			"open": "Any",
			"followup": ["Death's Door"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Medium Penalty",
			"effect": null
		},
		{
			"class": ["Nightshade"],
			"name": "Perforate Artery",
			"level": 21,
			"open": "In front of target, must be stealthed.",
			"followup": ["Creeping Death"],
			"end": "Low",
			"dmg": "Devastating",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": "32 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Achilles' Heel",
			"level": 25,
			"open": "Hamstring",
			"followup": ["Ripper"],
			"end": "Low",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's armor becomes 2% less effective for 30 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Leaper",
			"level": 29,
			"open": "Pincer",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Low BOnus",
			"def": "High Bonus",
			"effect": "Target's armor becomes 3% less effective for 30 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Creeping Death",
			"level": 34,
			"open": "Perforate Artery",
			"followup": ["Rib Separation"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Rib Separation",
			"level": 39,
			"open": "Creeping Death",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "High Penalty",
			"effect": "Target's armor becomes 3% less effective for 30 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Stunning Stab",
			"level": 44,
			"open": "Behind target",
			"followup": null,
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "Medium Penalty",
			"effect": "Target cannot move or take any other action for 6 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Death's Door",
			"level": 45,
			"open": "Garrote",
			"followup": null,
			"end": "High",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Target's armor becomes 2% less effective for 30 seconds."
		},
		{
			"class": ["Nightshade"],
			"name": "Ripper",
			"level": 50,
			"open": "Achilles' Heel",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "Very High Bonus",
			"def": "Medium Bonus",
			"effect": "Target's armor becomes 5% less effective for 30 seconds."
		}
	]
}

const CRUSH_SPEC_DATA = {
	"metaData": {
		"spec": "Crush",
		"type": "Combat",
		"weapon": "Crush",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Daze",
			"level": 1,
			"open": "Any",
			"followup": ["Crusher"],
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Crusher",
			"level": 2,
			"open": "Daze",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Back Crush",
			"level": 4,
			"open": "Behind target",
			"followup": ["Bruiser"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Maul",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Bludgeon",
			"level": 8,
			"open": "Any",
			"followup": ["Contusions"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Bruiser",
			"level": 10,
			"open": "Back Crush",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 3 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Concussion",
			"level": 12,
			"open": "You Parry",
			"followup": ["Hellfire Tendrils", "Bone Crusher"],
			"end": "Medium",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 18% for 20 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Contusions",
			"level": 15,
			"open": "Bludgeon",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Blackjack",
			"level": 18,
			"open": "In front of target",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Protector",
			"level": 25,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Divine Hammer",
			"level": 25,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Skull Breaker",
			"level": 29,
			"open": "You Block",
			"followup": ["Body Masher"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": null
		},
		{
			"class": ["Heretic"],
			"name": "Hellfire Tendrils",
			"level": 30,
			"open": "Concussion",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Penalty",
			"def": "Medium Bonus",
			"effect": "Your highest level Fiery Grasp is applied to all enemy targets within 200 units of your target.\n\nIf you have no Rejuvenation specialization, this style has no spell effect."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": " Side Crush",
			"level": 34,
			"open": "To side of target",
			"followup": ["Devastate"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 19 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Bone Crusher",
			"level": 39,
			"open": "Concussion",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Heretic", "Mercenary", "Paladin", "Reaver"],
			"name": "Body Masher",
			"level": 44,
			"open": "Skull Breaker",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Armsman", "Mercenary", "Paladin", "Reaver"],
			"name": "Devastate",
			"level": 50,
			"open": "Side Crush",
			"followup": null,
			"end": "High",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "Target's attack speed reduced by 30% for 20 seconds."
		},
		{
			"class": ["Heretic"],
			"name": "Shadowfire",
			"level": 50,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Does 113 heat damage to the target."
		}
	]
};

const DUAL_WIELD_SPEC_DATA = {
	"metaData": {
		"spec": "Dual Wield",
		"type": "Combat",
		"weapon": "Dual Wield",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Dual Strike",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Twin Spikes",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Twin Return",
			"level": 4,
			"open": "You Evade",
			"followup": ["Orbit"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Shadow's Edge",
			"level": 6,
			"open": "In front of target",
			"followup": ["Eclipse"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Inflame",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Orbit",
			"level": 10,
			"open": "Twin Return",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Eclipse",
			"level": 12,
			"open": "Shadow's Edge",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Infiltrator"],
			"name": "Misty Gloom",
			"level": 15,
			"open": "Any",
			"followup": null,
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Mercenary"],
			"name": "Flank",
			"level": 15,
			"open": "To side of target",
			"followup": ["Misty Gloom"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "Target moves 40% slower for 12 seconds."
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Obscure",
			"level": 18,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Infiltrator"],
			"name": "Penumbra",
			"level": 21,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Mercenary"],
			"name": "Penumbra",
			"level": 21,
			"open": "Behind target",
			"followup": ["Dual Shadows"],
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Reflection",
			"level": 25,
			"open": "You Evade",
			"followup": ["Hypnotic Darkness"],
			"end": "Low",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "Reduces the target's (AF) by 50 for 15 seconds."
		},
		{
			"class": ["Infiltrator"],
			"name": "Flank",
			"level": 29,
			"open": "To side of target",
			"followup": ["Shadow's Rain"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "Target moves 40% slower for 12 seconds."
		},
		{
			"class": ["Mercenary"],
			"name": "Misty Gloom",
			"level": 29,
			"open": "Flank",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "26 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Infiltrator", "Mercenary"],
			"name": "Dark Tendrils",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Infiltrator"],
			"name": "Shadow's Rain",
			"level": 39,
			"open": "Flank",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Mercenary"],
			"name": "Shadow's Rain",
			"level": 39,
			"open": "To side of target",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Infiltrator"],
			"name": "Hypnotic Darkness",
			"level": 44,
			"open": "Reflection",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Mercenary"],
			"name": "Hypnotic Darkness",
			"level": 44,
			"open": "Reflection",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		
		{
			"class": ["Infiltrator"],
			"name": "Dual Shadows",
			"level": 50,
			"open": "In front of target",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "26 damage every 4.0 sec for 20 seconds"
		},
		{
			"class": ["Mercenary"],
			"name": "Dual Shadows",
			"level": 50,
			"open": "Penumbra",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		}
	]
};

const FLEXIBLE_SPEC_DATA = {
	"metaData": {
		"spec": "Flexible",
		"altName": "Flex Weapons",
		"type": "Combat",
		"weapon": "Flexible",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Heretic", "Reaver"],
			"name": "Massasauga",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Blacksnake",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Kingsnake",
			"level": 4,
			"open": "You Block",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Diamondback",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Asp",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Very High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Viper",
			"level": 10,
			"open": "You Block",
			"followup": ["Copperhead"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": null
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Copperhead",
			"level": 12,
			"open": "Viper",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Tigersnake",
			"level": 15,
			"open": "You Parry",
			"followup": ["Anaconda"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 22% for 20 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Indigosnake",
			"level": 18,
			"open": "To side of target",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "The target takes 45 spirit damage and the attacker is healed for 70% of the damage dealt."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Boomslang",
			"level": 21,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 19 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Python",
			"level": 25,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "Decreases the target's strength by 30 for 30 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Taipan",
			"level": 29,
			"open": "To side of target",
			"followup": ["Cobra"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 23 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Constrictor",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Does 45 spirit damage to the target."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Anaconda",
			"level": 39,
			"open": "Tigersnake",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Cobra",
			"level": 44,
			"open": "Taipan",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Does 130 spirit damage to the target."
		},
		{
			"class": ["Heretic", "Reaver"],
			"name": "Leviathan",
			"level": 50,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Does 113 spirit damage to the target."
		}
	]
};

const LARGE_WEAPONRY_SPEC_DATA = {
	"metaData": {
		"spec": "Large Weaponry",
		"altName": "Large Weapons",
		"type": "Combat",
		"weapon": "Large Weaponry",
		"trainedValue": 1 
	},
	"styles": [
		{
			"class": ["Champion", "Hero"],
			"name": "Hibernian Might",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Celtic Might",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Celtic Rage",
			"level": 4,
			"open": "You Parry",
			"followup": ["Hibernian Vigor"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": null
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Celtic Fury",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Hibernian Wrath",
			"level":8 ,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Hibernian Force",
			"level": 10,
			"open": "In front of target",
			"followup": ["Obliteration"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Hibernian Vigor",
			"level": 12,
			"open": "Celtic Rage",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Domination",
			"level": 15,
			"open": "To side of target",
			"followup": null,
			"end": "High",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": "Target moves 40% slower for 12 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Obliteration",
			"level": 18,
			"open": "Hibernian Force",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 20% for 20 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Frontal Assault",
			"level": 21,
			"open": "In front of target",
			"followup": ["Shatter"],
			"end": "High",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Gigantic Blow",
			"level": 25,
			"open": "Behind target",
			"followup": ["Annihilation"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Ultimate Recovery",
			"level": 29,
			"open": "You Parry",
			"followup": ["Devastate"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Demolish",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Shatter",
			"level": 39,
			"open": "Frontal Assault",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Devastate",
			"level": 44,
			"open": "Ultimate Recovery",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "High Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Champion"],
			"name": "Annihilation",
			"level": 50,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Annihilation",
			"level": 50,
			"open": "Gigantic Blow",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "Target cannot move or take any other action for 9 seconds."
		}
	]
};

const PAINWORKING_STYLE_DATA = {
	"metaData": {
		"spec": "Painworking",
		"type": "Combat",
		"weapon": "Painworking",
		"trainedValue": 1//PAINWORKING_TRAINED_SPELL_DATA.metaData.trainedValue
	},
	"styles": [
		{
			"class": ["Necromancer"],
			"name": "Villainous Strike",
			"level": 1,
			"open": "Any",
			"followup": ["Chilling Touch"],
			"end": "Low",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target's armor becomes 1% less effective for 30 seconds."
		},
		{
			"class": ["Necromancer"],
			"name": "Chilling Touch",
			"level": 3,
			"open": "Villainous Strike",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "Medium Penalty",
			"effect": "Grants you 5% chance to evade melee and ranged physical attacks for 10 seconds."
		},
		{
			"class": ["Necromancer"],
			"name": "Shadow Beckon",
			"level": 13,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Low Bonus",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Necromancer"],
			"name": "Arctic Death",
			"level": 16,
			"open": "You Parry",
			"followup": ["Vanquisher"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Necromancer"],
			"name": "Icebringer",
			"level": 23,
			"open": "To side of target",
			"followup": ["Frostbite"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Inflicts a wasting disease on the target that slows target by 15%, reduces its strength by 15 and inhibits healing by 50% for 20 seconds."
		},
		{
			"class": ["Necromancer"],
			"name": "Vanquisher",
			"level": 26,
			"open": "Arctic Death",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Dissipates all ablative barriers from the target."
		},
		{
			"class": ["Necromancer"],
			"name": "Icy Cleave",
			"level": 33,
			"open": "In front of target",
			"followup": null,
			"end": "Very High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Strikes all enemies in front of you for 12 cold damage.\nRadius: 125"
		},
		{
			"class": ["Necromancer"],
			"name": "Frozen Edge",
			"level": 36,
			"open": "Behind target",
			"followup": ["Deathseeker"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Decreases the target's resistance to cold damage by 25% for 12 seconds."
		},
		{
			"class": ["Necromancer"],
			"name": "Frostbite",
			"level": 43,
			"open": "Icebringer",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		},
		{
			"class": ["Necromancer"],
			"name": "Deathseeker",
			"level": 46,
			"open": "Frozen Edge",
			"followup": null,
			"end": "High",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Imposes a -50.0% penalty to the effectiveness of heal spells cast by the target."
		}
	]
};

const PARRY_SPEC_DATA = {
	"metaData": {
		"spec": "Parry",
		"trainedValue": 1
	}
};

const PIERCING_SPEC_DATA = {
	"metaData": {
		"spec": "Piercing",
		"type": "Combat",
		"weapon": "Piercing",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Dragonfly",
			"level": 1,
			"open": "Any",
			"followup": ["Hornet"],
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Hornet",
			"level": 2,
			"open": "Dragonfly",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Nightshade", "Ranger"],
			"name": "Wildsting",
			"level": 3,
			"open": "Any, must be stealthed",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": null
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Wasp's Sting",
			"level": 4,
			"open": "In front of target",
			"followup": ["Hornet's Sting"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger"],
			"name": "Bumblebee's Sting",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "High Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Vampiir"],
			"name": "Vampiir's Sting",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "High Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Hornet's Sting",
			"level": 8,
			"open": "Wasp's Sting",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 18% for 20 seconds.'"
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Scorpion",
			"level": 10,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Vampiir"],
			"name": "Head Shot",
			"level": 11,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Medium Penalty",
			"effect": "Hits the target's helm."
		},
		{
			"class": ["Vampiir"],
			"name": "Torso Shot",
			"level": 12,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Medium Penalty",
			"effect": "Hits the target's chestpiece."
		},
		{
			"class": ["Blademaster", "Nightshade"],
			"name": "Black Widow",
			"level": 12,
			"open": "Behind target",
			"followup": ["Sidewinder"],
			"end": "High",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": null
		},
		{
			"class": ["Champion", "Hero", "Ranger", "Vampiir"],
			"name": "Black Widow",
			"level": 12,
			"open": "Behind Target",
			"followup": ["Sidewinder"],
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": "Target moves 40% slower for 12 seconds."
		},
		{
			"class": ["Vampiir"],
			"name": "Leg Shot",
			"level": 13,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Medium Penalty",
			"effect": "Hits the target's legs."
		},
		{
			"class": ["Blademaster", "Champion", "Hero"],
			"name": "Tarantula",
			"level": 15,
			"open": "You Block",
			"followup": ["Viper's Bite"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Nightshade", "Ranger"],
			"name": "Tarantula",
			"level": 15,
			"open": "You Evade",
			"followup": ["Viper's Bite"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Vampiir"],
			"name": "Tarantula",
			"level": 15,
			"open": "You Parry",
			"followup": ["Viper's Bite"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Sidewinder",
			"level": 18,
			"open": "Black Widow",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 21% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Copperhead",
			"level": 21,
			"open": "To side of target",
			"followup": ["Cobra's Bite"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Diamondback",
			"level": 25,
			"open": "You Evade",
			"followup": ["Dragonspider"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Viper's Bite",
			"level": 29,
			"open": "Tarantula",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Asp's Bite",
			"level": 34,
			"open": "Any",
			"followup": "Wyvern's Bite",
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": null
		},
		{
			"class": ["Champion", "Hero"],
			"name": "Asp's Bite",
			"level": 34,
			"open": "Any",
			"followup": ["Wyvern's Bite"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": null
		},
		{
			"class": ["Vampiir"],
			"name": "Asp's Bite",
			"level": 34,
			"open": "Any",
			"followup": ["Wyvern's Bite", "Vampiiric Feint", "Dark Vampiir Strike"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Cobra's Bite",
			"level": 39,
			"open": "Copperhead",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "26 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Vampiir"],
			"name": "Vampiir's Bite",
			"level": 40,
			"open": "Behind target",
			"followup": null,
			"end": "High",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "High Penalty",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Vampiir"],
			"name": "Vampiiric Feint",
			"level": 41,
			"open": "Asp's Bite",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "Your critical hit chance with spells is increased by 25% for 10 seconds."
		},
		{
			"class": ["Vampiir"],
			"name": "Eye Shot",
			"level": 43,
			"open": "In front of target",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": "Hits the target's helm."
		},
		{
			"class": ["Vampiir"],
			"name": "Lung Shot",
			"level": 44,
			"open": "To side of target",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Hits the target's chestpiece."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Nightshade", "Ranger", "Vampiir"],
			"name": "Dragonspider",
			"level": 44,
			"open": "Diamondback",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Vampiir"],
			"name": "Knee Cap",
			"level": 45,
			"open": "Behind target",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Hits the target's legs."
		},
		{
			"class": ["Blademaster", "Nightshade", "Ranger"],
			"name": "Wyvern's Bite",
			"level": 50,
			"open": "Asp's Bite",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 30% for 20 seconds."
		},
		{
			"class": ["Champion", "Hero", "Vampiir"],
			"name": "Wyvern's Bite",
			"level": 50,
			"open": "Asp's Bite",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 34% for 20 seconds."
		}
	]
};

const POLEARM_SPEC_DATA = {
	"metaData": {
		"spec": "Polearm",
		"type": "Combat",
		"weapon": "Polearm",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Armsman"],
			"name": "Pole Thrash",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman"],
			"name": "Impale",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Cross",
			"level": 4,
			"open": "To side of target",
			"followup": ["Disabler"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 11 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Deflect",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Faith",
			"level": 8,
			"open": "Any",
			"followup": ["Defender's Courage"],
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "Low Penalty",
			"effect": "4 damage every 5.0 sec for 25 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Executioner",
			"level": 10,
			"open": "You Parry",
			"followup": ["Defender's Advance"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Targets attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Distract",
			"level": 12,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Courage",
			"level": 15,
			"open": "Defender's Faith",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 20% for 20 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Crippling Blow",
			"level": 18,
			"open": "To side of target",
			"followup": ["Mangle"],
			"end": "Medium",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 11 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Disabler",
			"level": 21,
			"open": "Defender's Cross",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 21% for 20 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Phalanx",
			"level": 25,
			"open": "Behind target",
			"followup": ["Defender's Revenge"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Mangle",
			"level": 29,
			"open": "Crippling Blow",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 6 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Rage",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman"],
			"name": "Poleaxe",
			"level": 39,
			"open": "To side of target",
			"followup": ["Defender's Aegis"],
			"end": "High",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Revenge",
			"level": 44,
			"open": "Phalanx",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Very High Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 9 seconds."
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Advance",
			"level": 48,
			"open": "Executioner",
			"followup": null,
			"end": "High",
			"dmg": "Very High",
			"hit": "Low Bonus",
			"def": "Medium Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds"
		},
		{
			"class": ["Armsman"],
			"name": "Defender's Aegis",
			"level": 50,
			"open": "Poleaxe",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "32 damage every 4.0 sec for 20 seconds."
		}
	]
};

const SCYTHE_SPEC_DATA = {
	"metaData": {
		"spec": "Scythe",
		"type": "Combat",
		"weapon": "Scythe",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Valewalker"],
			"name": "Razorthorn",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Valewalker"],
			"name": "Reaper",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Valewalker"],
			"name": "Sawgrass",
			"level": 4,
			"open": "You Parry",
			"followup": ["Thorny Shield"],
			"end": "Low",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target becomes more vulnerable to your weapon by 15% for 20 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Taunting Scythe",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Valewalker"],
			"name": "Arboreal Fire",
			"level": 8,
			"open": "You Evade",
			"followup": ["Flaming Scythe"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Your melee attacks do 4.5 additional heat damage for 30 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Stunning Blade",
			"level": 10,
			"open": "To side of target",
			"followup": ["Blizzard Blade"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Foxfire",
			"level": 12,
			"open": "Behind target",
			"followup": ["Winter's Scythe"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 12 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Thorny Shield",
			"level": 15,
			"open": "Sawgrass",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "Low Bonus",
			"def": "High Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Winter's Scythe",
			"level": 18,
			"open": "Foxfire",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target's armor becomes 1% less effective for 30 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Arboreal Shield",
			"level": 21,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Valewalker"],
			"name": "Nature's Shield",
			"level": 25,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Grants attacker a 60% base chance to block incoming ranged physical attacks."
		},
		{
			"class": ["Valewalker"],
			"name": "Blizzard Blade",
			"level": 29,
			"open": "Stunning Blade",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Does 198 cold damage to the target.\n\nRadius: 350"
		},
		{
			"class": ["Valewalker"],
			"name": "Flaming Scythe",
			"level": 32,
			"open": "Arboreal Fire",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Does 57 heat damage to the target.\n\nRadius: 350"
		},
		{
			"class": ["Valewalker"],
			"name": "Grasping Roots",
			"level": 34,
			"open": "In front of target",
			"followup": ["Conflagration"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "High Bonus",
			"effect": "The target is rooted in place for 10 seconds.\n\nRadius: 350"
		},
		{
			"class": ["Valewalker"],
			"name": "Damaging Grasp",
			"level": 39,
			"open": "Behind target",
			"followup": ["Snow Blade"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Valewalker"],
			"name": "Snow Blade",
			"level": 43,
			"open": "Damaging Grasp",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Does 125 cold damage to the target."
		},
		{
			"class": ["Valewalker"],
			"name": "Conflagration",
			"level": 50,
			"open": "Grasping Roots",
			"followup": null,
			"end": "High",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "Medium Penalty",
			"effect": "Does 150 heat damage to the target."
		}		
	]
};

const SHIELD_SPEC_DATA = {
	"metaData": {
		"spec": "Shield",
		"type": "Combat",
		"weapon": "Shield",
		"trainedValue": 1
	},
	"spells": [
		{
			"class": ["Hero"],
			"name": "Tactics",
			"level": 45,
			"duration": "30 seconds",
			"target": "Group",
			"range": 1500,
			"castTime": "Instant",
			"effect": "Increases the target's chance to parry, block and evade.",
			"addEffect": "\nDoes not grant these abilities if the target doesn't have them already.",
			"reuse": {
				"level": 1,
				"timer": "10 minutes"
			}
		},
	],
	"styles": [
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Smash",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Numb",
			"level": 3,
			"open": "Any",
			"followup": null,
			"end": "High",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 2 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Stun",
			"level": 8,
			"open": "You Block",
			"followup": null,
			"end": "High",
			"dmg": "High",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 3 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Disable",
			"level": 13,
			"open": "To side of target",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 4 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Incapacitate",
			"level": 18,
			"open": "You Block",
			"followup": null,
			"end": "Very High",
			"dmg": "High",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Paralyze",
			"level": 23,
			"open": "Behind target",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 6 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Bash",
			"level": 29,
			"open": "You Block",
			"followup": null,
			"end": "High",
			"dmg": "High",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		}, 
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Mangle",
			"level": 35,
			"open": "To side of target",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Champion"],
			"name": "Pin",
			"level": 40,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target moves 70% slower for 6 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Shield Swipe",
			"level": 41,
			"open": "Any",
			"followup": null,
			"end": "High",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Hits up to 16 additional targets within melee range."
		},
		{
			"class": ["Blademaster", "Champion", "Warden"],
			"name": "Slam",
			"level": 42,
			"open": "Any",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Hero"],
			"name": "Slam",
			"level": 42,
			"open": "Any",
			"followup": null,
			"end": "Very High",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 9 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Immobolize",
			"level": 44,
			"open": "To side of target",
			"followup": null,
			"end": "High",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Low Bonus",
			"effect": "Target moves 40% slower for 21 seconds."
		},
		{
			"class": ["Warden"],
			"name": "Cripple",
			"level": 46,
			"open": "Behind target",
			"followup": null,
			"end": "Very High",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "Low Bonus",
			"effect": "Target moves 40% slower for 23 seconds."
		},
		{
			"class": ["Blademaster", "Champion", "Hero", "Warden"],
			"name": "Brutalize",
			"level": 50,
			"open": "You Block",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 10 seconds."
		}
	]
};

const SLASH_SPEC_DATA = {
	"metaData": {
		"spec": "Slash",
		"type": "Combat",
		"weapon": "Slash",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Ruby Slash",
			"level": 1,
			"open": "Any",
			"followup": ["Emerald Slash"],
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Emerald Slash",
			"level": 2,
			"open": "Ruby Slash",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 seconds for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Cross Slash",
			"level": 4,
			"open": "In front of target",
			"followup": ["Bloodletter"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Uppercut",
			"level": 6,
			"open": "Any",
			"followup": ["Opal Slash", "Cleave"],
			"end": "Medium",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Enrage",
			"level": 8,
			"open": "Any",
			"followup": ["Sapphire Slash"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "No Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Bloodletter",
			"level": 10,
			"open": "Cross Slash",
			"followup": null,
			"end": "Medium",
			"dmg": "Low",
			"hit": "High Bonus",
			"def": "Medium Bonus",
			"effect": "13 damage every 4.0 seconds for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Reflect",
			"level": 12,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Opal Slash",
			"level": 15,
			"open": "Uppercut",
			"followup": null,
			"end": "Medium",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "13 damage every 4.0 seconds for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Riposte",
			"level": 18,
			"open": "You Block",
			"followup": ["Befuddler"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Medium Bonus",
			"effect": "Target's attack speed reduced by 21% for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Side Slicer",
			"level": 21,
			"open": "To side of target",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 14 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Cleave",
			"level": 25,
			"open": "Uppercut",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "20 damage every 4.0 seconds for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Amethyst Slash",
			"level": 29,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Befuddler",
			"level": 34,
			"open": "Riposte",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 6 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Back Slash",
			"level": 39,
			"open": "Behind target",
			"followup": ["Diamond Slash"],
			"end": "High",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 19 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Sapphire Slash",
			"level": 44,
			"open": "Enrage",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "High Penalty",
			"effect": "26 damage every 4.0 seconds for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Diamond Slash",
			"level": 50,
			"open": "Back Slash",
			"followup": null,
			"end": "High",
			"dmg": "High",
			"hit": "Very High Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 34% for 20 seconds."
		}
	]
};

const STAFF_SPEC_DATA = {
	"metaData": {
		"spec": "Staff",
		"type": "Combat",
		"weapon": "Staff",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Friar"],
			"name": "Spinning Staff",
			"level": 1,
			"open": "Any",
			"followup": ["Jabbing Staff"],
			"end": "Low",
			"dmg": "Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Jabbing Staff",
			"level": 4,
			"open": "Spinning Staff",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "You regain 10 hit points."
		},
		{
			"class": ["Friar"],
			"name": "Defender's Fury",
			"level": 8,
			"open": "You Parry",
			"followup": ["Friar's Fury"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "Medium Bonus",
			"effect": "Target's attack speed reduced by 20% for 20 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Quick Strike",
			"level": 10,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Friar"],
			"name": "Friar's Redress",
			"level": 12,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Very High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Friar"],
			"name": "Double Strike",
			"level": 15,
			"open": "To side of target",
			"followup": ["Banish"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Friar's Friend",
			"level": 18,
			"open": "Behind target",
			"followup": null,
			"end": "High",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 27 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Counter Evade",
			"level": 25,
			"open": "You Evade",
			"followup": ["Figure Eight"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Increases the target's attack speed by 20% for 15 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Banish",
			"level": 29,
			"open": "Double Strike",
			"followup": null,
			"end": "Very High",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Does 175 spirit damage to the target.\n\nRadius: 350"
		},
		{
			"class": ["Friar"],
			"name": "Holy Staff",
			"level": 34,
			"open": "Any",
			"followup": ["Excommunicate"],
			"end": "High",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "The target regenerates 50 health every 2.0 sec for 10 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Friar's Fury",
			"level": 28,
			"open": "Defender's Fury",
			"followup": null,
			"end": "Very High",
			"dmg": "High",
			"hit": "Medium",
			"def": "Low Bonus",
			"effect": "Target cannot move or take any other action for 8 seconds."
		},
		{
			"class": ["Friar"],
			"name": "Figure Eight",
			"level": 44,
			"open": "Counter Evade",
			"followup": null,
			"end": "High",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "Low Bonus",
			"effect": "Increases your Staff by 10% for 1 minute."
		},
		{
			"class": ["Friar"],
			"name": "Excommunicate",
			"level": 50,
			"open": "Holy Staff",
			"followup": null,
			"end": "High",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "You do an additional 75 spirit damage to your target and heal your group for 125."
		}
	]
};

const THRUST_SPEC_DATA = {
	"metaData": {
		"spec": "Thrust",
		"type": "Combat",
		"weapon": "Thrust",
		"trainedValue": 1
	},
	"styles": [
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Thistle",
			"level": 1,
			"open": "Any",
			"followup": ["Sever"],
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Sever",
			"level": 2,
			"open": "Thistle",
			"followup": null,
			"end": "Low",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Infiltrator", "Minstrel", "Scout"],
			"name": "Wildcat",
			"level": 3,
			"open": "Any, must be stealthed",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Ratfang",
			"level": 4,
			"open": "You Parry",
			"followup": ["Wolftooth"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Puncture",
			"level": 6,
			"open": "Any",
			"followup": ["Bloody Dance"],
			"end": "High",
			"dmg": "Low",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Sting",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "High Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Wolftooth",
			"level": 10,
			"open": "Ratfang",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 5 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Bloody Dance",
			"level": 12,
			"open": "Puncture",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "Low Penalty",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Beartooth",
			"level": 15,
			"open": "You Block",
			"followup": ["Lunge"],
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 20% for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Tranquillize",
			"level": 18,
			"open": "Any",
			"followup": ["Wyvernfang"],
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "Medium Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Lunge",
			"level": 21,
			"open": "Beartooth",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Ricochet",
			"level": 25,
			"open": "You Block",
			"followup": ["Dragonfang"],
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Pierce",
			"level": 29,
			"open": "Behind target",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "Target moves 40% slower for 15 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Liontooth",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "Low Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Basiliskfang",
			"level": 39,
			"open": "To side of target",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "Low Bonus",
			"effect": "Target's attack speed reduced by 30% for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Wyvernfang",
			"level": 44,
			"open": "Tranquillize",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 30% for 20 seconds."
		},
		{
			"class": ["Armsman", "Infiltrator", "Mercenary", "Minstrel", "Paladin", "Reaver", "Scout"],
			"name": "Dragonfang",
			"level": 50,
			"open": "Ricochet",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "High Bonus",
			"def": "Low Penalty",
			"effect": "Target cannot move or take any other action for 8 seconds."
		}
	]
};

const TWO_HANDED_SPEC_DATA = {
	"metaData": {
		"spec": "Two Handed",
		"type": "Combat",
		"weapon": "Two Handed",
		"trainedValue": 1,
	},
	"styles": [
		{
			"class": ["Armsman", "Paladin"],
			"name": "Quarter Moon",
			"level": 1,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Half Moon",
			"level": 2,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Very Low",
			"hit": "No Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Double Back",
			"level": 4,
			"open": "In front of target",
			"followup": ["Two Fists"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 16% for 20 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Rile",
			"level": 6,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "Medium Penalty",
			"effect": "Increases your threat to monster targets by 275 damage."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Pacify",
			"level": 8,
			"open": "Any",
			"followup": null,
			"end": "Low",
			"dmg": "None",
			"hit": "No Bonus",
			"def": "High Bonus",
			"effect": "Increases your threat to monster targets by 0 damage."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Two Fists",
			"level": 10,
			"open": "Double Back",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "8 damage every 5.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Bone Bruiser",
			"level": 12,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Low",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "Target's attack speed reduced by 18% for 20 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Onslaught",
			"level": 15,
			"open": "To side of target",
			"followup": ["Two Moons"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 14 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Fury",
			"level": 18,
			"open": "You Parry",
			"followup": ["Recenter"],
			"end": "Low",
			"dmg": "Medium",
			"hit": "High Bonus",
			"def": "High Penalty",
			"effect": "13 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Bone Splitter",
			"level": 21,
			"open": "In front of target",
			"followup": ["Bone Breaker"],
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Recenter",
			"level": 25,
			"open": "Fury",
			"followup": null,
			"end": "Low",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "High Bonus",
			"effect": "Target's attack speed reduced by 26% for 20 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Bone Breaker",
			"level": 29,
			"open": "Bone Splitter",
			"followup": null,
			"end": "Medium",
			"dmg": "High",
			"hit": "Low Bonus",
			"def": "No Bonus",
			"effect": "20 damage every 4.0 sec for 20 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Obfuscate",
			"level": 34,
			"open": "Any",
			"followup": null,
			"end": "Medium",
			"dmg": "Medium",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": null
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Doubler",
			"level": 39,
			"open": "Behind target",
			"followup": ["Sun and Moon"],
			"end": "Medium",
			"dmg": "High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target moves 40% slower for 23 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Two Moons",
			"level": 44,
			"open": "Onslaught",
			"followup": null,
			"end": "Low",
			"dmg": "Very High",
			"hit": "High Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 9 seconds."
		},
		{
			"class": ["Armsman", "Paladin"],
			"name": "Sun and Moon",
			"level": 50,
			"open": "Doubler",
			"followup": null,
			"end": "Medium",
			"dmg": "Very High",
			"hit": "Medium Bonus",
			"def": "No Bonus",
			"effect": "Target cannot move or take any other action for 7 seconds."
		}
	]
};



/*  style template
		{
			"class": [""],
			"name": "",
			"level": ,
			"open": "",
			"followup": ,
			"end": "",
			"dmg": "",
			"hit": "",
			"def": "",
			"effect":
		}
*/